name: deployment
on: [push]

jobs:
    Linting_application:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            
            - name: Install Dependencies
              run: npm ci 

            - name: Run Lint
              run: npm run lint


    Testing_application:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            
            - name: Install Dependencies
              run: npm ci 

            - name: Run Test
              run: npm run test


    deploy_application:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            
            - name: Install Dependencies
              run: npm ci 

            - name: Build Application
              run: npm run build

